import RPi.GPIO as GPIO
import time

lightningPin = 18 #GPIO18
GPIO.setmode(GPIO.BCM)
GPIO.setup(lightningPin, GPIO.OUT)



time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)
time.sleep(2)
GPIO.output(lightningPin, 1)
time.sleep(2)
GPIO.output(lightningPin, 0)